contract:
  senderAddress: ${contract.senderAddress}
  fee: 0
  contractVersion: 1
  version: 2
  image: ${contract.image}
  imageHash: ${contract.imageHash}
  contractName: game-contract

node:
  credentials:
    senderAddress: {node.credentials.senderAddress}
  feign:
    url: ${node.feign.url}
    decode404: true
    connectTimeout: 5000
    readTimeout: 3000
server:
  port: 8080
